### ISSUE TITLE
Fetcher failure: Fetch command failed with exit code 128

### ISSUE THREAD

**Issue by ppladde** [intel-iot-devkit/meta-iot-cloud#156]
I am using Krogoth branch of Yocto for my development and I need to add "pycryptodome" to my build.
layers.openembedded.org redirected me here for that recipe.
I have copied entire "meta-iot-cloud" layer and added the same to my "bblayer.conf". then added "python3-pycryptodome" to my local.conf. but there is some fetch error when I try to bitbake. 
Can someone please point out what I am missing.  Below is the bitbake error message outpute.

`WARNING: python3-pycryptodome-3.4.5-r0 do_fetch: Failed to fetch URL git://github.com/Legrandin/pycryptodome.git, attempting MIRRORS if available
ERROR: python3-pycryptodome-3.4.5-r0 do_fetch: Fetcher failure: Fetch command failed with exit code 128, output:
Cloning into bare repository '/home/pravin/MYD-Y6ULX-devel/fsl-release-yocto/downloads//git2/github.com.Legrandin.pycryptodome.git'...
fatal: unable to connect to github.com:
github.com[0: 20.207.73.82]: errno=Connection timed out`

**Comment by srware** [comment]
It's likely this is due to Github no longer allowing access through the git protocol or some other issue with the repository commit being pulled by the recipe. I imagine updating the recipe to use https protocol would fix things. That said, given the krogoth release is 5 years past end of life there are likely to be many other issues.
